### PR TITLE
fix bug issue #4 and add issue #5

### PR DESCRIPTION
**Pull request by alex1702**

### CODE REVIEW

**Comment by alex1702** [comment]
add roster from andrea11 and fix bugs, add readme lines. And add get roster function.

**Comment by alex1702** [comment]
fix wrong variable name bug in add_user function.

**Comment by wltsmrz** [comment]
Hey @alex1702, sorry this hasn't gotten attention. I've added you as a collaborator to this repository.

**Comment by alex1702** [comment]
ok

**Pull request merged**
